### ISSUE TITLE
Add some use for poisonous potatoes

### ISSUE THREAD

**Issue by MainGameCentral** [Jiingy/Jineric-Mod#30]
Whether it be an easter egg or an actual feature, poisonous potatoes need a use. Badly

**Comment by Jiingy** [comment]
Seems like a good idea. Don't know yet what we could do for it though.

**Comment by MainGameCentral** [comment]
Yeah, we'll need to think on it for a bit

**Comment by Jiingy** [comment]
I actually came up with an idea for this

What if the storage block we add for poisonous potatoes makes passive mobs run away from it just like how hoglins run from warped fungus? Could be useful for passive mob farming and could be argued that it's balanced since poisonous potatoes aren't exactly "easy" to get. 

I'd like to imaging a cenario where people are actively trying to get poisonous potatoes for something like this

**Comment by Jiingy** [comment]
Closed in favor of Trello posts
