### ISSUE TITLE
Make template files for crafting recipes

### ISSUE THREAD

**Issue by MrCheeze446** [Jiingy/Jineric-Mod#52]
This is literally just to make our lives easier:
- [ ] stair block in crafting table
- [ ] stair block in stonecutter
- [ ] slab in crafting table
- [ ] slab in stonecutter
- [ ] wall in crafting table
- [ ] wall in stonecutter

**Comment by Deviouslrd** [comment]
Regarding those crafting table recipes, i have a preset/quick generate for crafting table recipes with 1 ingredient.

So, when I finish crafting table recipes (probably shouldn't be too long), ill make a proper release and then you got both at your disposal.

But for now, go ahead doing it manually, as I have no timeline for release + completion of crafting tables.

**Comment by MrCheeze446** [comment]
oh that'd be amazing, I'll probably still end up making the template files for just incase the tool ever breaks, however that's great news!

**Comment by Jiingy** [comment]
It's a bit hard to make a template considering you have to do a ton of renaming as crafting recipes can either have jineric assets, minecraft assets, you'd have to rename the block texture, and also would need multiple templates for blocks that have the same texture on all faces and for ones that have custom texture maps. 

Personally I don't really see this being worth it to do as I can imagine it causing more of a headache rather than a relief with improperly renaming the template. I say for now we just use Devious' tool and if we see the template as a better idea later on down the road we can make them.

**Comment by Jiingy** [comment]
Marked this with shelved for now, gonna close it as like I said a few days ago I really don't see this being too useful.
