### ISSUE TITLE
Fix up textures for new walls/stairs/slabs

### ISSUE THREAD

**Issue by MrCheeze446** [Jiingy/Jineric-Mod#54]
- [ ] cut sandstone
- [ ] cut red sandstone
- [x] soul sandstone
- [x] smooth stone (Not going to do as it would require far too many textures)

**Comment by Jiingy** [comment]
Unfortunately as far as I'm aware, because of how Mojang added walls you can't have custom top/bottom/side textures. Basically Mojang = bad. 

This is what I have now, I can try to fix the slabs and stairs but like I said I think walls are gonna be a no-go.
![2021-02-09_00 50 14](https://user-images.githubusercontent.com/69827559/107338960-fb4de680-6a70-11eb-97a6-3ba7b590e9c0.png)

**Comment by Jiingy** [comment]
Closing cause I don't see this as necessary or possible anymore
